### PR TITLE
Sphinx documentation for opm-simulators and GitHub action

### PR DESCRIPTION
**Pull request by hakonhagland**
This was taken from https://github.com/OPM/opm-simulators/pull/5243

### CODE REVIEW

**Comment by lisajulia** [comment]
Nice :) Then we can we also include the following from https://github.com/OPM/opm-simulators/pull/5349, right?
- documentation for opm_embedded
- documentation for opm common
- renaming the signature of the functions to "opm.simulators.BlackOilSimulator.__init__(deck_filename: str) -> None" such that the methods get structured automatically by sphinx

**Comment by hakonhagland** [comment]
> Then we can we also include the following from https://github.com/OPM/opm-simulators/pull/5349, right?

Yes, that is the plan :) Feel free to submit a PR here based on that PR.

**Comment by hakonhagland** [comment]
@lisajulia If @akva2 does not have any comments, I thinks this PR can be merged?

**Comment by lisajulia** [comment]
> @lisajulia If @akva2 does not have any comments, I thinks this PR can be merged?

Yes :)

**Comment by lisajulia** [comment]
> > Then we can we also include the following from [OPM/opm-simulators#5349](https://github.com/OPM/opm-simulators/pull/5349), right?
> 
> Yes, that is the plan :) Feel free to submit a PR here based on that PR.

Perfect, I'll do that then

**Review by lisajulia — APPROVED** [review]

**Comment by lisajulia** [comment]
@hakonhagland can I merge this then?

**Pull request merged**
